runtime: java17
instance_class: F2
env_variables:
  JAVA_OPTS: "-Xms512m -Xmx2g"
automatic_scaling:
  min_idle_instances: 1   # Keeps at least 1 idle instance running
  max_idle_instances: 2   # Allows a maximum of 2 idle instances
  min_pending_latency: 30ms  # Ensures that new instances start within this latency
  max_pending_latency: 300ms # Maximum time to wait before starting a new instance
  max_instances: 4  