INSERT INTO public.workout (created_at, id, image_name, show_sequence, workout) VALUES('2024-04-04 01:32:09.808', 1, 'chest_home.jpg', '1', 'Chest');
INSERT INTO public.workout (created_at, id, image_name, show_sequence, workout) VALUES('2024-04-04 01:32:09.808', 2, 'back_home.jpg', '2', 'Back');
INSERT INTO public.workout (created_at, id, image_name, show_sequence, workout) VALUES('2024-04-04 01:32:09.808', 3, 'biceps_home.jpg', '3', 'Biceps');
INSERT INTO public.workout (created_at, id, image_name, show_sequence, workout) VALUES('2024-04-04 01:32:09.808', 4, 'shoulder_home.jpg', '4', 'Shoulder');
INSERT INTO public.workout (created_at, id, image_name, show_sequence, workout) VALUES('2024-04-04 01:32:09.808', 5, 'tricep_home.jpg', '5', 'Triceps');
INSERT INTO public.workout (created_at, id, image_name, show_sequence, workout) VALUES('2024-04-04 01:32:09.808', 6, 'abs_home.jpg', '6', 'Abs');
INSERT INTO public.workout (created_at, id, image_name, show_sequence, workout) VALUES('2024-04-04 01:32:09.808', 7, 'legs_home.jpg', '7', 'Legs');
INSERT INTO public.workout (created_at, id, image_name, show_sequence, workout) VALUES('2024-04-04 01:32:09.808', 8, 'hamstring_home.jpg', '8', 'Hamstring');
INSERT INTO public.workout (created_at, id, image_name, show_sequence, workout) VALUES('2024-04-04 01:32:09.808', 9, 'glutes_home.jpg', '9', 'Glutes');


-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------


INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:32:58.446', 1, NULL, NULL, NULL, 'Bench Press', 'BenchPress.gif', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:32:58.446', 2, NULL, NULL, NULL, 'Cable Low Fly', 'CableLowFly.gif', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:32:58.446', 3, NULL, NULL, NULL, 'Cable Standing Fly', 'CableStandingFly.gif', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:32:58.446', 4, NULL, NULL, NULL, 'Chest Dip', 'ChestDip.gif', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:32:58.446', 6, NULL, NULL, NULL, 'Fly', 'Fly.gif', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:32:58.446', 7, NULL, NULL, NULL, 'Incline Bench Press', 'InclineBenchPress.gif', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:32:58.446', 8, NULL, NULL, NULL, 'Incline Dumbbell Bench Press', 'InclineDumbbellBenchPress.gif', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:32:58.446', 9, NULL, NULL, NULL, 'Incline Fly', 'InclineFly.gif', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:32:58.446', 10, NULL, NULL, NULL, 'Lever Seated Fly', 'LeverSeatedFly.gif', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:32:58.446', 11, NULL, NULL, NULL, 'Pullover', 'Pullover.gif', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:32:58.446', 12, NULL, NULL, NULL, 'Push-up', 'Push-up.gif', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:32:58.446', 5, NULL, NULL, NULL, 'Dumbbell Bench Press', 'DumbellBenchPress.gif', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 14, NULL, NULL, NULL, 'Overhead Triceps Extension', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 16, NULL, NULL, NULL, 'Dip on Floor with Chair', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 17, NULL, NULL, NULL, 'High Pulley Overhead Tricep Extension', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 18, NULL, NULL, NULL, 'Standing Tricep Extension', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 19, NULL, NULL, NULL, 'Close-grip Push-up', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 21, NULL, NULL, NULL, 'Seated bench Extension', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 22, NULL, NULL, NULL, 'Triceps Dip', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 23, NULL, NULL, NULL, 'Close-Grip Bench Press', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 25, NULL, NULL, NULL, 'Bench Dip', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 26, NULL, NULL, NULL, 'Lever Seated Dip', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 27, NULL, NULL, NULL, 'Kickback', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 13, NULL, NULL, NULL, 'Triceps Pushdown', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:36:53.427', 24, NULL, NULL, NULL, 'Cable Triceps Pushdown', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:44:57.705', 28, NULL, NULL, NULL, 'Bar Lateral Pulldown', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:44:57.705', 29, NULL, NULL, NULL, 'Barbell Bent Over Row', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:44:57.705', 30, NULL, NULL, NULL, 'Bent over Row', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:44:57.705', 31, NULL, NULL, NULL, 'Cable Standing Lat Pushdown', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:44:57.705', 32, NULL, NULL, NULL, 'Lat Pull Down Closed Grip', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:44:57.705', 33, NULL, NULL, NULL, 'Lateral Pull-Down V-Bar', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:44:57.705', 35, NULL, NULL, NULL, 'Pull-up', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:44:57.705', 36, NULL, NULL, NULL, 'Seated Back Row Straight', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:44:57.705', 37, NULL, NULL, NULL, 'Wide Grip Lat Pull Down', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:46:03.370', 38, NULL, NULL, NULL, 'Lateral Raise', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:46:03.370', 39, NULL, NULL, NULL, 'Seated Shoulder Press', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:46:03.370', 40, NULL, NULL, NULL, 'Lever Seated Shoulder Press', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:46:03.370', 41, NULL, NULL, NULL, 'Front Raise', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:46:03.370', 42, NULL, NULL, NULL, 'Lever Seated Reverse Fly', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:46:03.370', 44, NULL, NULL, NULL, 'Arnold Press', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:46:03.370', 45, NULL, NULL, NULL, 'Dumbbell Seated Shoulder Press', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:46:03.370', 46, NULL, NULL, NULL, 'Dumbbell Rear Delt Fly', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:46:03.370', 43, NULL, NULL, NULL, 'Barbell Standing Military Press', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:52:13.271', 47, NULL, NULL, NULL, 'Cable Kneeling Crush', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:52:13.271', 48, NULL, NULL, NULL, 'Crunch Floor', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:52:13.271', 49, NULL, NULL, NULL, 'Decline Crunch', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:52:13.271', 50, NULL, NULL, NULL, 'Dumbbell Side Bend', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:52:13.271', 51, NULL, NULL, NULL, 'Hanging Leg Hip Raise', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:52:13.271', 52, NULL, NULL, NULL, 'Hyperextension', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:52:13.271', 53, NULL, NULL, NULL, 'Lying Leg Raise', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:52:13.271', 54, NULL, NULL, NULL, 'Plank', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:52:13.271', 55, NULL, NULL, NULL, 'Russian Twist', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:52:13.271', 56, NULL, NULL, NULL, 'Side Plank', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:52:13.271', 57, NULL, NULL, NULL, 'Straight Leg Raise', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:52:13.271', 58, NULL, NULL, NULL, 'Weighted Russian Twist', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:02.126', 59, NULL, NULL, NULL, 'Bulgarian Split Squat', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:02.126', 60, NULL, NULL, NULL, 'Bulgarian Split Squats Dumbbell', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:02.126', 61, NULL, NULL, NULL, 'Full Squats', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:02.126', 62, NULL, NULL, NULL, 'Leg Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:02.126', 63, NULL, NULL, NULL, 'Leg Wide Press', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:02.126', 64, NULL, NULL, NULL, 'Lever Kneeling Leg Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:02.126', 65, NULL, NULL, NULL, 'Lever Leg Extension', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:02.126', 66, NULL, NULL, NULL, 'Lunges', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:02.126', 67, NULL, NULL, NULL, 'Lunges Walking', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:02.126', 68, NULL, NULL, NULL, 'Sled Hack Squats', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:02.126', 69, NULL, NULL, NULL, 'Sqauts', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:39.662', 70, NULL, NULL, NULL, 'Dumbbell Lying Hamstring Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:39.662', 71, NULL, NULL, NULL, 'Lever Kneeling Leg Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:39.662', 72, NULL, NULL, NULL, 'Lever Lying Leg Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:39.662', 73, NULL, NULL, NULL, 'Lever Seated Leg Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:39.662', 74, NULL, NULL, NULL, 'Lying Femoral', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:39.662', 75, NULL, NULL, NULL, 'Seated Single Leg Hamstring', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 11:59:39.662', 76, NULL, NULL, NULL, 'Straight Leg Deadlift', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:00:23.874', 77, NULL, NULL, NULL, 'Deadlift', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:00:23.874', 78, NULL, NULL, NULL, 'Dumbbell Bar Grip Sumo Squat', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:00:23.874', 79, NULL, NULL, NULL, 'Dumbbell Glute Bridge', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:00:23.874', 81, NULL, NULL, NULL, 'Dumbbell Single Leg Deadlift', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:00:23.874', 82, NULL, NULL, NULL, 'Hip Thrust', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:00:23.874', 83, NULL, NULL, NULL, 'Lever Seated Hip Abduction', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:00:23.874', 84, NULL, NULL, NULL, 'Romanian Deadlift', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:00:23.874', 85, NULL, NULL, NULL, 'Romanian Deadlift Dumbbell', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:00:23.874', 86, NULL, NULL, NULL, 'Sled 45 Degree Leg Press', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:00:23.874', 87, NULL, NULL, NULL, 'Sled Hack Squat', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:00:23.874', 88, NULL, NULL, NULL, 'Sumo Deadlift', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:02:27.015', 89, NULL, NULL, NULL, 'Biceps Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:02:27.015', 90, NULL, NULL, NULL, 'Barbell Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:02:27.015', 91, NULL, NULL, NULL, 'Alternate Biceps Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:02:27.015', 93, NULL, NULL, NULL, 'Concentration Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:02:27.015', 94, NULL, NULL, NULL, 'Dumbbell Incline Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:02:27.015', 95, NULL, NULL, NULL, 'EZ Barbell Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:02:27.015', 96, NULL, NULL, NULL, 'EZ Barbell Spider Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:02:27.015', 97, NULL, NULL, NULL, 'Hammer Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:02:27.015', 98, NULL, NULL, NULL, 'Lever Preacher Curl', '', '3-5', NULL, NULL);
INSERT INTO public.exercise (created_at, id, claories_burned, exercise_description, exercise_duration, exercise_name, gif_name, set_range, show_sequence, image_name) VALUES('2025-01-30 12:02:27.015', 99, NULL, NULL, NULL, 'Preacher Curl', '', '3-5', NULL, NULL);

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------


INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(1, 1);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(2, 1);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(3, 1);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(4, 1);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(5, 1);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(6, 1);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(7, 1);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(8, 1);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(9, 1);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(10, 1);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(11, 1);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(12, 1);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(13, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(14, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(16, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(17, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(18, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(19, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(21, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(22, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(23, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(24, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(25, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(26, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(27, 5);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(38, 4);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(39, 4);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(40, 4);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(41, 4);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(42, 4);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(43, 4);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(44, 4);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(45, 4);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(46, 4);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(47, 6);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(48, 6);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(49, 6);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(50, 6);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(51, 6);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(52, 6);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(53, 6);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(54, 6);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(55, 6);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(56, 6);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(57, 6);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(58, 6);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(59, 7);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(60, 7);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(61, 7);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(62, 7);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(63, 7);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(64, 7);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(65, 7);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(66, 7);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(67, 7);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(68, 7);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(69, 7);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(70, 8);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(71, 8);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(72, 8);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(73, 8);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(74, 8);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(75, 8);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(76, 8);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(77, 9);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(78, 9);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(79, 9);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(81, 9);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(82, 9);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(83, 9);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(84, 9);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(85, 9);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(86, 9);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(87, 9);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(88, 9);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(89, 3);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(90, 3);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(91, 3);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(93, 3);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(94, 3);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(95, 3);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(96, 3);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(97, 3);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(98, 3);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(99, 3);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(28, 2);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(29, 2);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(30, 2);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(31, 2);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(32, 2);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(33, 2);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(35, 2);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(36, 2);
INSERT INTO public.workout_exercises (exercise_id, workout_id) VALUES(37, 2);

---------------------------------------------------------------------------------------------