jwt:
  authorities:
    key: roles
  expiration: 86400000
  header:
    string: Authorization
  refreshExpiration: 9000000
  secret: gymfitappsecraw2873219
  signing:
    key: signingkey
  token:
    prefix: 'Bearer '
server:
  port: ${PORT:8086}
spring:
  application:
    name: gymfitnew
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/gym_fit?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
build:
   version: 1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always
  metrics:
    enabled: true
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true

